server:
  port: 3080
spring:
  banner:
    location: classpath:banner.txt
  application:
    name: ledger
  profiles:
    active: dev
config:
  credentialConfigFilePath: .oci/secrets-config
  customConfigFilePath: .oci/custom-config
allowedMethods: OPTIONS,GET,POST,PUT,DELETE
allowedHeaders: authorization,content-type