server:
  port: 3080
spring:
  banner:
    location: classpath:banner.txt
  application:
    name: ledger
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
    port: 587
config:
  credentialConfigFilePath: .oci/secrets-config
  customConfigFilePath: .oci/custom-config
allowedMethods: OPTIONS,GET,POST,PUT,DELETE
allowedHeaders: authorization,content-type